name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
      
      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyze
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings

